Removed BOSS and FOMM
ModOrganizer2/modorganizer-game_falloutnv pull request #29
Opened 2024-05-14 22:20 UTC by Twinki14

# Authors
- @Senjay-id
- @Ungeziefi

# Motivations
This plugin is particularly dated in several different spots, so a general update is needed

# Modifications
- Remove FOMM & BOSS, these are extremely dated and no longer maintained or used
- Rename Construction Kit to GECK, which is more well known
- Add all FNV DLC's to the primary plugin list, at this point you can't really buy FNV anymore without getting all it's DLC's

2024-05-14 22:47 UTC, Silarn commented
I'll go with the general consensus on this but I personally feel like having the support isn't a bad thing. There are definitely going to be old school people still using these things and the fact that we display the application if it exists isn't telling a new user to go download them. The only way it shows up is if someone already installed it.

As far as Creation Kit vs GECK, I'm ambivalent. I mean 'Creation Kit' is in the name so I don't see it as being that different or confusing.

2024-05-14 22:48 UTC, Twinki14 commented
> I'll go with the general consensus on this but I personally feel like having the support isn't a bad thing. There are definitely going to be old school people still using these things and the fact that we display the application if it exists isn't telling a new user to go download them. The only way it shows up is if someone already installed it.
> 
> As far as Creation Kit vs GECK, I'm ambivalent. I mean 'Creation Kit' is in the name so I don't see it as being that different or confusing.

I agree, but that's generally why we have versioning; If there are old-schoolers out there, they can use older versions of the plugin

2024-05-14 22:50 UTC, Silarn commented
Well the thing is MO2 plugins are fairly tied to the MO2 version. Any changes to the plugin ABI are going to break older builds, leaving anyone that wants the support but wants an updated MO2 out in the cold. I think we're kind of bad about updating plugin versions in general, but that's a different issue.

2024-05-14 22:52 UTC, Twinki14 commented
Fair point, but couldn't old schoolers still add their FOMM or BOSS executables manually? MO2 will still be supporting that

2024-05-15 06:41 UTC, Holt59 commented
Regarding the list of executables, I don't really see any positive point in removing the old ones (adding GECK, sure). If the executables cannot be found, they will not be displayed anyway.

Regarding the plugins, what would be the benefits of marking them as primary? If we do so, you'll need to remove them from `DLCPlugins`. I'm personally not really for this since I like seeing my DLCs as DLCs, but that might be subjective.

If we decide to go with the changes, you'll need to fix the formatting issues.

2024-05-15 15:31 UTC, Silarn commented
Yeah I didn't see or fully consider the DLC change. While I understand the intent, I don't think it's necessarily appropriate to cater only to people who are just buying the game new. It's still entirely possible to have an old copy of NV / FO3 / etc. and these plugins are, as far as I know, still not hard coded to load with the game in a specific order.

Flagging DLC plugins doesn't just indicate that they're installed as DLC but it has implications about how they can be loaded or ordered in the plugin list. Generally primary plugins should be ones which the game loads automatically and will cause it to fail if they don't exist.

2024-05-15 15:42 UTC, Silarn requested changes

2024-05-15 15:42 UTC, Silarn commented on src/gamefalloutnv.cpp
> +      << ExecutableInfo("GECK", findInGameFolder("geck.exe"))
You can keep the 'GECK' name change I suppose, but I think we'd prefer to keep the other executables for legacy reasons. They will only populate if these applications were already installed by the user so there's no clear reason to remove a convenience layer here.

2024-05-15 15:42 UTC, Silarn commented on src/gamefalloutnv.cpp
> +  return {
I think we're going to remove this for now. There are both technical and legacy reasons to leave this alone and there are use cases for FNV players to allow them to toggle and reorder the DLCs if they want to. TTW is a different matter.

2024-05-15 16:02 UTC, Twinki14 commented
PR has been re-focused into just the GECK name change

2024-05-15 16:59 UTC, Holt59 approved these changes

2024-05-17 15:04 UTC, Silarn approved these changes

2024-05-17 15:04 UTC, merged